テキストの変更
skisnosuke/battle pull request #29
Opened 2022-02-20 06:43 UTC by skisnosuke

# Issue
fixed #28 
# 内容
- ログを変更

2022-02-22 01:22 UTC, eteRnaL198 requested changes
難しいね

2022-02-22 01:22 UTC, eteRnaL198 commented on character.py
> +  def incantation(self, target):
メソッド名は動詞がいいかな
cast_spell とか

2022-02-22 01:22 UTC, eteRnaL198 commented on character.py
> +    self.settings = Settings()
このクラスでは設定を読み込むのではなく､初期化する時の引数に渡すようにしてほしい｡
self.magics 属性を作って､その中にメラを入れるみたいな｡
そうすればホイミとか追加しやすくなる｡
```
magics {
  mera: {
    消費MP: bar
    攻撃力: baz
  },
  hoimi: {
    以下略
}
```
みたいな辞書型が良さげ

2022-02-22 01:22 UTC, eteRnaL198 commented on character.py
> +      self.mp -= self.settings.mera
これだとメラ専用になってるから､汎用性を高めてほしい｡
cast_spell(self, target, damage)みたいにダメージを引数に渡すとか｡
呼び出す側でメラを指定した方が､後に使いやすそうな気がする｡

2022-02-22 01:22 UTC, eteRnaL198 commented on command.py
> +      player.incantation(target)
番号で場合分けするのはわかりにくいから､別の方法探したい｡｡
何の呪文を唱えるかの情報も含めたいし｡ うーん｡｡

2022-02-22 04:54 UTC, syunnta917 commented on command.py
> +      player.incantation(target)
実際のゲームってこういう場合分けはどうしてるんだろうね
考えてみたけど番号での場合分けぐらいしか思いつかなかったや
で、incantationの中身(?)で呪文の選択をまた番号で…っていう複雑な感じのしか思いつかない

2022-02-22 04:56 UTC, syunnta917 requested changes

2022-02-22 04:56 UTC, syunnta917 commented on log.py
> +      "ゆうしゃは 呪文を唱えた",
はちゃめちゃに細かいけど、漢字のフォントってあるのかな
ひらがなの方がいいのかもしれない
初代もひらがなだし確か

2022-02-22 05:06 UTC, eteRnaL198 commented on command.py
> +      player.incantation(target)
俺が書いたんだけど、行動の番号がcommandと logで使われてて、かなり煩雑。
番号じゃなくて辞書形式にして、かつ階層は浅くなるようにしたい

2022-02-22 15:40 UTC, skisnosuke commented on character.py
> +  def incantation(self, target):
https://github.com/skisnosuke/battle/pull/29/commits/e91ec3da8cc4e2ff94988c9d6db4084dcd11928a
修正しました

2022-02-22 16:12 UTC, skisnosuke commented on character.py
> +    self.settings = Settings()
https://github.com/skisnosuke/battle/pull/29/commits/a3140f13f6fc97356c88a23611a8c1b78ecdde11
修正しました。
呪文の選び方を考えてないのでメラ固定になってます

2022-02-22 17:25 UTC, skisnosuke commented on log.py
> +     (tuple(map(lambda n: n+16, self.settings.log_position+self.settings.log_length))))
ログ表示させようとしてたやつです。無視してください。

2022-02-23 00:06 UTC, eteRnaL198 requested changes
ちょこっと修正お願いします

2022-02-23 00:06 UTC, eteRnaL198 commented on settings.py
> +        self.spells = {"メラ":{"消費MP":2, "ダメージ":10}}
俺がコメントしといてなんだけど、キーは英語でお願い
あと、player_spellsがいいかも。敵の呪文も追加しやすくなる

2022-02-23 00:06 UTC, eteRnaL198 commented on character.py
> +    self.settings = Settings()
設定はもう読み込まなくて大丈夫

2022-02-23 00:14 UTC, eteRnaL198 commented on log.py
> +     (tuple(map(lambda n: n+16, self.settings.log_position+self.settings.log_length))))
自分で確認した系はコメントアウトでお願いします
俺もどこかに確認したやつ残しちゃってた気がする

2022-02-23 00:22 UTC, eteRnaL198 commented on character.py
> +      target.reduce_hp(self.spells[spell]["ダメージ"])
こーゆー書き方できるの忘れてた。めっちゃいい

2022-02-23 00:57 UTC, eteRnaL198 requested changes
追加で

2022-02-23 00:57 UTC, eteRnaL198 commented on main.py
> +                                self.flag = False
- 条件重複してる。ほとんど削除で
  ```
  self.flag = True
  while self.flag
  if self.command.action_selected == 0:
    hoge
  elif bar
    baz
  ```
  でいい。
- flagだと何を判定してるのか分かりにくいから、`isBazBar`または`canFooBar`がよい。
  そもそもこのwhile文は何のためにあるの？

2022-02-23 00:57 UTC, eteRnaL198 commented on main.py
> +                                    self.incantation_sound.play()
呪文は`spell`で統一した方が分かりやすい

2022-02-23 03:11 UTC, syunnta917 commented on settings.py
> +
一通り眺めてみたけど難しい要素が多くて勉強になります
ここはこうした方がいいよとかは指摘できないけど、if文ってやっぱりどうしても多くなっちゃうものなんですかね
俺も何か書くときif文滅茶苦茶入れちゃうタイプなんだけど、冗長じゃないか恐れながら書いてた

2022-02-23 03:12 UTC, syunnta917 commented on log.py
> +      "ゆうしゃは 呪文を唱えた",
確認しました！
お疲れ様でやんす

2022-02-25 10:41 UTC, skisnosuke commented on main.py
> +                                self.flag = False
修正前に説明だけしときます。
たたかう、じゅもんのどちらかの行動でEnter_keyが押されたときに、1回目でlogの変更とカーソル音、2回目で呪文の効果音とダメージ音を入れたかったのでそのためのkey入力を待つためのwhileループです。

2022-02-25 14:19 UTC, skisnosuke commented on main.py
> +                                self.flag = False
https://github.com/skisnosuke/battle/pull/29/commits/ab4cc31d368bbea33b93459d89f0543605d8f06e
修正しました。
幾つか関数にまとめてみました。
Enter_keyだけでなく、どのkeyでも反応するようにしました。

2022-02-25 14:22 UTC, skisnosuke commented on character.py
> +    self.settings = Settings()
https://github.com/skisnosuke/battle/pull/29/commits/f0ebefc6c120a7e6097febb9fc5a49413d2b833d
忘れてた！ありがとう！
修正完了です。

2022-02-25 14:29 UTC, skisnosuke commented on log.py
> +     (tuple(map(lambda n: n+16, self.settings.log_position+self.settings.log_length))))
https://github.com/skisnosuke/battle/pull/29/commits/ab4cc31d368bbea33b93459d89f0543605d8f06e
了解です。
あと該当箇所の修正しときました。

2022-02-25 14:38 UTC, skisnosuke commented on settings.py
> +        self.spells = {"メラ":{"消費MP":2, "ダメージ":10}}
https://github.com/skisnosuke/battle/pull/29/commits/d94c579079efbca7a67ade3188028aa17f09936c
修正しました。
見落としあるかもしれないからもし見つけたら連絡ください。

2022-02-25 14:40 UTC, eteRnaL198 commented on main.py
> +                                self.flag = False
コミットを分けてくれると見やすいです orz

2022-02-25 14:47 UTC, skisnosuke commented on main.py
> +                                    self.incantation_sound.play()
https://github.com/skisnosuke/battle/pull/29/commits/83f77a2542b515d41894290b42356632bb0ec4b0
修正しました。

2022-02-25 15:05 UTC, eteRnaL198 commented on main.py
> +                                self.flag = False
キー入力は待たなくていいんじゃないかな

2022-03-02 01:21 UTC, eteRnaL198 approved these changes
LGTM

2022-03-02 11:17 UTC, syunnta917 approved these changes

2022-03-02 17:38 UTC, skisnosuke commented on log.py
> -    self.text = self.font.render("スライムが あらわれた！", False, (255, 255, 255))
ここの表示が出てなかったやつ触れられてなかった。
修正感謝です!

2022-03-02 17:44 UTC, skisnosuke commented on sound.py
> +
soundクラスの作成感謝。関数名の _ 抜くことを忘れないの流石です!

2022-03-03 01:01 UTC, merged