呪文のテストの追加
skisnosuke/battle pull request #34
Opened 2022-03-04 12:47 UTC by skisnosuke

# Issue
fixed #30
# 内容
- cast_spellの動作確認

2022-03-06 01:38 UTC, eteRnaL198 requested changes

2022-03-06 01:38 UTC, eteRnaL198 commented on test/test.py
> +  def test_player_cast_spell_reduce_enemy_hp_by_mera_damage(self):
`player_cast_spell`を単数系の名詞として、`reduce`ではなく`reduces`がいいかな

2022-03-06 01:38 UTC, eteRnaL198 commented on test/test.py
> +    player = Character(10, "p", 1, 0, player_spells) # (attack, name, hp, mp)
呪文使わないから、引数は`(10, "p", 1, 0, {})`でいいかも
コメントアウトに`.., mp, spells`の追加をお願い

2022-03-07 03:47 UTC, skisnosuke commented on test/test.py
> +  def test_player_cast_spell_reduce_enemy_hp_by_mera_damage(self):
https://github.com/skisnosuke/battle/pull/34/commits/b2cb9ca3540a494f66a6244d62b9d04d632013db
修正しました。
コミット忘れてて、遅くなってごめん。

2022-03-07 03:49 UTC, skisnosuke commented on test/test.py
> +    player = Character(10, "p", 1, 0, player_spells) # (attack, name, hp, mp)
https://github.com/skisnosuke/battle/pull/34/commits/3aa30f82a4e52a5f86d7e71ed6ac5c0dc2616abf
修正しました!
下に実行結果載せときます。

----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK

2022-03-12 13:37 UTC, eteRnaL198 approved these changes

2022-10-16 11:13 UTC, merged